server:
  port: 4455
spring:
  datasource:
    url: jdbc:mysql://localhost:2005/JPA?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: true
